direct_reply = {
    '/start': '👋 Hello! How can I assist you today?',
    '/help': 'ℹ️ Use /new to create a new job\n🛠️ Cron generator online: http://indika.rf.gd/crongen.html',
}

strings = {
    'ask_post_link': '🔗 Alright, please send me the post link to share.',
    'ask_group_list': '📄 Ok, now send me the groups JSON file.',
    'invalid_group_list': '❌ Invalid group list. Please send a valid JSON file.',
    'ask_share_text': '✍️ Great, now send me the share text.',
    'cancelled': '🚫 Cancelled.',
    'cron_help': '🕒 Usage: /cron job_id crontab_expression',
    'cron_added': '✅ Cron job added successfully!',
    'cron_invalid': '❌ Invalid Job ID or crontab expression.',
    'cron_id_invalid': '❌ Invalid Cron ID.',
    'cron_deleted': '🗑️ Cron task deleted.',
    'job_deleted': '🗑️ Job deleted.',
    'delete_help': '🗑️ Usage: /del JOB|CRON id',
    'job_invalid': '❌ Invalid Job ID.',
    'unknown_command': '❓ Unknown command.',
    'active_jobs': '📋 Active Jobs:',
    'no_jobs': '🚫 No active jobs.',
    'group_list': '📄 Group List:',
    'share_text': '✍️ Share Text:',
    'del_cron': '🗑️ Deleted Cron.',
    'delbtn_cron': '🗑️ Delete Cron',
    'delbtn_job': '🗑️ Delete Job',
    'del_job': '🗑️ Deleted Job.',
    'confirm': '❓ Are you sure?',
    'edit_success': '✅ Field edited successfully!',
    'back': '🔙 Back',
    'edit': '✏️ Edit Field',
}